language: node_js

sudo: required

node_js:
  - "8.11"

env:
  - CXX=g++-4.8

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8
      - software-properties-common

before_install:
  - export CXX="g++-4.8"
  - npm update
  - sudo apt update
  - npm install -g npm@latest
  - npm install -g truffle
  - npm install -g solium
  - docker pull mythril/myth

install:
  - npm install 

script:
  - node_modules/.bin/solidity-coverage
  - solium -d contracts/
  - docker run mythril/myth --truffle

notifications:
  slack:
    on_success: always