language: node_js

sudo: required

node_js:
  - "8.11"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8
      - software-properties-common
      - "python3"
      - "python3-pip"

before_install:
  - export CXX="g++-4.8"
  - npm update
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt update
  - sudo apt install -y solc
  - sudo apt install libssl-dev
  - sudo npm install -g npm@latest
  - sudo npm install -g truffle
  - sudo npm install -g solium
  - pip3 install mythril

install:
  - npm install 


script:
  - ./node_modules/.bin/solidity-coverage